apiVersion: v1
kind: Secret
metadata:
  name: burger-secrets
  namespace: burger
type: Opaque
stringData:
  MYSQL_USER: "burgeruser"
  MYSQL_PASSWORD: "burgerpass"
  SESSION_SECRET: "change-me-in-real-life"
