apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: burger-ingress
  namespace: burger
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "1m"
spec:
  ingressClassName: nginx
  rules:
    - host: burger.localtest.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: burger-web
                port:
                  number: 80
